# PATH: backend/app/main.py
#
# PURPOSE:
#   The FastAPI application entry point.
#   This is the file Uvicorn runs to start the API server.
#
# WHAT IT DOES:
#   1. Creates the FastAPI app instance
#   2. Configures CORS so the React frontend can call the API
#   3. Creates all database tables on startup (via SQLAlchemy)
#   4. Registers all routers (each router adds a group of endpoints)
#   5. Adds a health-check endpoint at GET /health
#
# TO RUN LOCALLY:
#   uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
#
# INTERACTIVE API DOCS (auto-generated by FastAPI):
#   http://localhost:8000/docs   → Swagger UI
#   http://localhost:8000/redoc  → ReDoc

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.core.config import settings
from app.core.database import engine, Base, SessionLocal

# Import all models so SQLAlchemy knows about them before create_all()
import app.models  # noqa: F401

# Import all routers
from app.routers.agents    import router as agents_router
from app.routers.llm       import router as llm_router
from app.routers.tools     import router as tools_router
from app.routers.skill     import router as skill_router
from app.routers.tasks     import router as tasks_router
from app.routers.task_runs import router as task_runs_router
from app.routers.dashboard import router as dashboard_router
from app.routers.dashboard import router as workflows_router

# ── Create the FastAPI app ────────────────────────────────────────────────────
app = FastAPI(
    title=settings.APP_NAME,
    description="Backend API for the AI Workflow",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# ── CORS middleware ───────────────────────────────────────────────────────────
# Allows the React frontend (running on localhost:3000 or :5173) to call this API.
# In production, replace with your actual frontend domain.
app.add_middleware(
    CORSMiddleware,
    #allow_origins=["http://localhost:5173"]
    allow_origins = settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Startup: create tables, then seed default data ────────────────────────────
@app.on_event("startup")
def on_startup():
    # 1. Create all tables that don't exist yet (safe / idempotent)
    Base.metadata.create_all(bind=engine)

    # 2. Seed default agents, tools, LLM configs if the DB is empty
    db = SessionLocal()
    try:
        from app.core.seed import seed_database
        seed_database(db)
    except Exception as exc:
        print(f"[startup] Seed warning: {exc}")
    finally:
        db.close()


@app.get("/")
def root():
    return {"message": "AI Workflow API is running"}
# ── Create DB tables on startup ───────────────────────────────────────────────
# In production you should use Alembic migrations instead of create_all().
# But this is fine for development — it creates any tables that don't exist yet.
@app.on_event("startup")
def create_tables():
    print("DATABASE URL:", settings.DATABASE_URL)
    Base.metadata.create_all(bind=engine)

@app.get("/test")
def test():
    return {"message": "Backend is connected successfully 🚀"}

# ── Register routers ──────────────────────────────────────────────────────────
# Each router adds a group of related endpoints to the app.
# The prefix is already defined inside each router file.
app.include_router(agents_router)     # /agents/*
app.include_router(llm_router)        # /llm/*
app.include_router(tools_router)      # /tools/*
app.include_router(skill_router)      # /skills/*
app.include_router(tasks_router)      # /tasks/*
app.include_router(task_runs_router)  # /task-runs/*
app.include_router(dashboard_router)  # /dashboard/*
app.include_router(workflows_router)  # /worflows/*
 
# ── Health check ──────────────────────────────────────────────────────────────
@app.get("/health", tags=["Health"])
def health_check():
    """Simple endpoint to verify the API is running. Used by Docker healthchecks."""
    return {"status": "ok", "app": settings.APP_NAME}